/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyconverter;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CurrencyConverte extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyConverte
     */
    public CurrencyConverte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Convert = new javax.swing.JButton();
        txtFrom = new javax.swing.JComboBox<>();
        txtTo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Currency Conveter");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Amount");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("To");

        Convert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Convert.setText("Convert");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        txtFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "BD TK", "Indian Rupees", "Russian Ruble", "Chinese Yuan", "Nepalese Rupee", "Bhutanese Ngultrum" }));
        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });

        txtTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "BD TK", "Indian Rupees", "Russian Ruble", "Chinese Yuan", "Nepalese Rupee", "Bhutanese Ngultrum" }));
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        // TODO add your handling code here:
        Double convert;
        Double amount = Double.parseDouble(txtAmount.getText());
        
        //USD
        
        if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 110.06;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 83.24;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 95.45;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 7.32;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 132.75;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 82.97;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        
        //INDIAN RUPEES...................................................................................................
        
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 1.32;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.012;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.011;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 1.15;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.088;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1.59;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Indian Rupees " && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        
        //EUR
        
        else if(txtFrom.getSelectedItem().toString()=="EUR" && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 116.71;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="EUR" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 88.27;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="EUR" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 1.06;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="EUR" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="EUR" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 1.15;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="ERU" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.088;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="ERU" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1.59;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="ERU " && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        
        //BD TAKA......................................................................................................
        
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 0.76;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.0091;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.0086;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 0.87;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.066;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1.21;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="BD TK" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 1.23;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        //RUSSIAN RUBLE...................................................................................................
        
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 1.15;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 0.87;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.010;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.0099;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.077;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1.39;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Russian Ruble" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 0.87;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        //Chinese Yuan................................................................................................
        
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan " && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 15.04;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 11.38;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.14;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.13;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 13.29;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 18.14;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Chinese Yuan" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 11.38;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
              
        //Nepalese Rupee...............................................................................................
        
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee " && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 0.83;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 0.63;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.0075;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.0071;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 0.72;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.055;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Nepalese Rupee" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 0.63;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
              
        ///Bhutanese Ngultrum.....................................................................................................
        
        
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum " && txtTo.getSelectedItem().toString()=="BD TK"){
            convert = amount * 1.33;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" BD TK");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="Indian Rupees"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Indian Rupees");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="USD"){
            convert = amount * 0.012;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" USD");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="EUR"){
            convert = amount * 0.011;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" EUR");
            
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="Russian Ruble"){
            convert = amount * 1.15;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Russian Ruble");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="Chinese Yuan"){
            convert = amount * 0.088;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Chinese Yuan");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="Nepalese Rupee"){
            convert = amount * 1.60;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Nepalese Rupee");
            
        }
        else if(txtFrom.getSelectedItem().toString()=="Bhutanese Ngultrum" && txtTo.getSelectedItem().toString()=="Bhutanese Ngultrum"){
            convert = amount * 1;
            JOptionPane.showMessageDialog(this,"This amount is: "+convert.toString()+" Bhutanese Ngultrum");
            
        }
        
        
        
        
    }//GEN-LAST:event_ConvertActionPerformed

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JComboBox<String> txtFrom;
    private javax.swing.JComboBox<String> txtTo;
    // End of variables declaration//GEN-END:variables
}
